{{- if regexMatch "^external[ -]?secret$" (lower .Values.secretProvider) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "chart.fullname" . }}-secret-store
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: sa-creds
          key: key
          namespace: {{ .Values.externalSecret.namespace }}
---          
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" . }}-external-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "chart.fullname" . }}-secret-store
    kind: ClusterSecretStore
  target:
    name:  {{ include "chart.fullname" . }}-secret
    labels:
      app.kubernetes.io/name: {{ include "chart.name" . }}
      helm.sh/chart: {{ include "chart.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  data:
    {{- range $key, $value := .Values.private_env_variables }}
    - secretKey: {{ $key }} 
      remoteRef:
        key: {{ $.Values.externalSecret.id }}
        property: {{ $key }}
    {{- end }}
{{- end }}